services:

  web:

    build: .

    ports:

      - "5000:5000"

    volumes:

      # Mount only GUI and instance so compiled C++ library inside image is preserved

      - ./gui:/app/gui

      - ./instance:/app/instance

    environment:

      - FLASK_APP=gui

      - FLASK_ENV=development

      - PYTHONPATH=/app/src

      - REDIS_URL=redis://redis:6379/

    depends_on:

      - redis

    restart: unless-stopped



  redis:

    image: "redis:alpine"

    ports:

      - "6379:6379"

    restart: unless-stopped



  worker:

    build: .

    command: rq worker

    working_dir: /app

    volumes:

      # Do not mount src to avoid overwriting compiled interface.so

      - ./gui:/app/gui

      - ./instance:/app/instance

    environment:

      - PYTHONPATH=/app/src

      - REDIS_URL=redis://redis:6379/

    depends_on:

      - redis

    deploy:

      replicas: 3

    restart: unless-stopped

  

  nginx:

    image: nginx:alpine

    ports:

      - "80:80"

    volumes:

      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:

      - web

    restart: unless-stopped
