version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=gui
      - FLASK_ENV=development
      - PYTHONPATH=/app:/app/src
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: rq worker
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app:/app/src
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
    deploy:
      replicas: 1