services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=gui
      - FLASK_ENV=development
      - PYTHONPATH=/app:/app/src
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: unless-stopped

  worker:
    build: .
    command: rq worker
    working_dir: /app/src
    environment:
      - PYTHONPATH=/app:/app/src
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - redis
    deploy:
      replicas: 3
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    restart: unless-stopped